export enum PostgresDataTypes {
  INTEGER = 'integer',
  BIGINT = 'bigint',
  DECIMAL = 'decimal',
  NUMERIC = 'numeric',
  REAL = 'real',
  DOUBLE_PRECISION = 'double precision',
  VARCHAR = 'character varying',
  CHAR = 'character',
  TEXT = 'text',
  TIMESTAMP = 'timestamp',
  DATE = 'date',
  TIME = 'time',
  INTERVAL = 'interval',
  BOOLEAN = 'boolean',
  INTEGER_ARRAY = 'integer[]',
  TEXT_ARRAY = 'text[]',
  JSON = 'json',
  JSONB = 'jsonb',
  UUID = 'uuid',
  HSTORE = 'hstore',
}
